env:
  BASE_TAG: "sbt-update-lines-base-${BUILDKITE_COMMIT}"

steps:
  - name: ":sbt: Store version and meta data"
    command: .buildkite/store-version-metadata

  - name: ":docker: :quay: Build and push base"
    agents:
      queue: docker
    plugins:
      vital-software/docker-compose#vital-v2.5:
        config:
          - docker-compose.yml
          - docker-compose.buildkite.yml
        build: sbt-update-lines-base
        image_repository: quay.io/vital/build-cache
        image-name: ${BASE_TAG}

  - wait

  - name: ":scala: Run tests"
    command: sbt -batch -v test
    timeout_in_minutes: 5
    plugins:
      vital-software/metadata-env#v0.0.1:
        get: [SBT_VERSION, GIT_COMMITTED_AT]
      vital-software/docker-compose#vital-v2.5:
        config:
          - docker-compose.yml
          - docker-compose.buildkite.yml
        run: sbt-update-lines-base
        log_all: true

  - name: ":sbt: Run sbt scripted tests"
    command: sbt -batch -v scripted
    timeout_in_minutes: 5
    plugins:
      vital-software/metadata-env#v0.0.1:
        get: [SBT_VERSION, GIT_COMMITTED_AT]
      vital-software/docker-compose#vital-v2.5:
        config:
          - docker-compose.yml
          - docker-compose.buildkite.yml
        run: sbt-update-lines-base
        log_all: true

  - wait: ~
    continue_on_failure: true

  - name: ":scala: Report on compile problems"
    command: .buildkite/report-compile-problems

# Marker: version-release
  - wait

  - block: ":rocket: Release"
    prompt: Create a release, and push it to Github?
    branches: "master ci/release"

  - name: ":sbt: Release new version"
    branches: master
    command:
      - git checkout -B ${BUILDKITE_BRANCH}
      - git branch -u origin/${BUILDKITE_BRANCH}
      - git config branch.${BUILDKITE_BRANCH}.remote origin
      - git config branch.${BUILDKITE_BRANCH}.merge refs/heads/${BUILDKITE_BRANCH}
      - git clean -df
      - sbt -batch "release with-defaults skip-tests"
    plugins:
      - seek-oss/aws-sm#v2.2.1:
          json-to-env:
            - secret-id: "global/bintray-credentials"
              json-key: ".Variables"
